# Generated by Django 3.0 on 2019-12-11 16:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockReading',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_id', models.TextField(validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(13)])),
                ('expiration_date', models.DateTimeField()),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockReadingHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expiration_date', models.DateTimeField()),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StockReading')),
            ],
        ),
    ]
